package org.jboss.demo.customersatisfaction;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(79b78a8c97f9bb1f567165be9d31c8d9)
 */
@org.kie.api.definition.type.Label(value = "Customer Information")
public class Customer extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Call comments")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String callComments;

    @org.kie.api.definition.type.Label(value = "Customer comments")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String customerComments;

    @org.kie.api.definition.type.Label(value = "Email")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String email;

    @org.kie.api.definition.type.Label(value = "Customer Name")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String name;

    @org.kie.api.definition.type.Label(value = "Phone")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String phone;

    @org.kie.api.definition.type.Label(value = "tweeterId")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String tweeterId;

    public Customer() {
    }

    public Customer(java.lang.String customerComments, java.lang.String phone, java.lang.String name, java.lang.String tweeterId, java.lang.String callComments, java.lang.String email) {
        this.customerComments = customerComments;
        this.phone = phone;
        this.name = name;
        this.tweeterId = tweeterId;
        this.callComments = callComments;
        this.email = email;
    }



    public java.lang.String getCallComments() {
        return this.callComments;
    }

    public void setCallComments(java.lang.String callComments) {
        this.callComments = callComments;
    }

    public java.lang.String getCustomerComments() {
        return this.customerComments;
    }

    public void setCustomerComments(java.lang.String customerComments) {
        this.customerComments = customerComments;
    }

    public java.lang.String getEmail() {
        return this.email;
    }

    public void setEmail(java.lang.String email) {
        this.email = email;
    }

    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getPhone() {
        return this.phone;
    }

    public void setPhone(java.lang.String phone) {
        this.phone = phone;
    }

    public java.lang.String getTweeterId() {
        return this.tweeterId;
    }

    public void setTweeterId(java.lang.String tweeterId) {
        this.tweeterId = tweeterId;
    }
}